### ISSUE TITLE
Virtual Keyboard malfunction after update dev 2704

### ISSUE THREAD

**Issue by uwahl** [milikhin/seabass2#144] opened 2022-07-09 09:28 UTC
[uwahl](https://forums.ubports.com/user/uwahl)
[vor 17 Stunden](https://forums.ubports.com/post/65596)

After doing the above update (Nexus5, dev channel update to 2407) the keyboard doesn't respond anymore when tapping characters in seabass2 editor. Backspace still answering. In Dekko2 for exemple, the keyboard seems still responding normally on all keys.
When changing back to stable channel, this strange behaviour doesn't occur any more.
When changing to dev again, the phenomenon can be reproduced...

Any ideas?

**Comment by milikhin** [comment] 2022-07-10 06:50
Thank you very much for opening an issue and letting me know about the problem!

My guess would be that dev channel has browser engine updated from QtWebEngine 5.12 to 5.15.
Seabass for Ubuntu Touch uses [Ace](ace.c9.io) as editor component and then QtWebEngine to render Ace, so I'm pretty sure that it's updated QtWebEngine that caused the issue.

I'm not sure what could be done here though:
- I don't currently have a device running Ubuntu Touch to check if my guess is correct or verify possible workarounds for the issue.
- There is an updated version of Seabass in the works that replaces Ace with [Codemirror](https://codemirror.net/6). The change should probably fix the problem, but it is work in progress and is not yet ready to be released to the Open Store. In fact, initially I didn't plan to release it anytime soon because of missing features, but it might has just become the only viable option now :-)

Summarizing all the above:

- the issue is probably related to the QtWebEngine update is is probably going to persist in dev channel for now
- hopefully there is still some time before the next stable OTA update that will contain breaking QtWebEngine changes
- if so, we might see a new major Seabass release that will fix the issue before the breaking changes will land to the UT's stable channel :-)
- if so, such Seabass release will contain most basic features in place with notable exclusions being support for QML syntax highlight, find/replace and code snippets.

**Comment by milikhin** [comment] 2022-09-10 07:46
I wonder if it is still an issue, or maybe something has been fixed on Ubuntu Touch side?

**Closed** 2022-10-08 15:57 UTC

**Comment by uwahl** [comment] 2022-10-11 08:39
Thank you very much for your kind answer!

The behaviour of the keyboard is strange - when playing around, I found 
that there is something like a timeout when tapping a character: For 
exemple when I tap an "R" and wait then for about a second, the keyboard 
is totally blocked; only exception is the backspace key... But when I'm 
tapping very fast the "R" I am able to get more "r"'s and sometime the 
keyboard then is even deblocked and hitting keys in normal speed is 
possible...

Strange, isn't ist?

By the way, thank you very much for your work!!!!

**Comment by uwahl** [comment] 2022-10-11 09:20
o.k. for me on nexus5.
more annoying when tapping a number, the keybord jumping back to chrakters immediately. no chance to keep on hitting numbers...

Am Sat, 10 Sep 2022 00:47:07 -0700, Mikhail Milikhin schrieb:
> I wonder if it is still an issue, or maybe something has been 
> fixed on Ubuntu Touch side?
>

--
