### ISSUE TITLE
Make automatic word wrapping optional

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#36] opened 2020-05-30 18:10 UTC
Sometimes displaying a text file without word wrapping can be convenient. Horizontal scrolling seems to work flawlessly.

**Comment by milikhin** [comment] 2020-06-04 05:32
Thank you for the issue!

I've tested horizontal scrolling for the first release.
It had performance issues on SFOS.

> Horizontal scrolling seems to work flawlessly.

Please note that correct horizontal scrolling in Ace Editor (`wrap: false` option) is different from the behaviour caused by scaling issues in #34. Please correct me if you've modified the source code to check that proper horizontal scrolling works fine!

For now this issues is a `wontfix` at least until SFOS webview is updated with better hardware acceleration for CSS animations.

**Closed by milikhin** 2020-06-04 05:32 UTC
Labels: wontfix

**Comment by Pohli** [comment] 2020-06-04 17:38
I'm not a coder, so indeed I mean the flawless scrolling caused by scaling issues in #34.
